import { notFound } from "next/navigation";
import { articles, consultant, getArticle } from "../../../../lib/felipe";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const article = getArticle((await params).slug); if (!article) return {};
  return { title: `${article.title} | Felipe Soares | ES11 Capital`, description: article.excerpt, alternates: { canonical: `/consultores/felipe-soares/artigos/${article.slug}` } };
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const article = getArticle((await params).slug); if (!article) notFound();
  const related = articles.filter((item) => item.slug !== article.slug).slice(0, 2);
  const jsonLd = { "@context": "https://schema.org", "@type": "BlogPosting", headline: article.title, description: article.excerpt, datePublished: article.publishedAt, dateModified: article.updatedAt, image: article.image, author: { "@type": "Person", name: consultant.name, url: consultant.profileUrl }, publisher: { "@type": "Organization", name: "ES11 Capital", url: "https://www.es11capital.com.br/" } };
  return <main className="reader-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><header className="reader-header"><a href="/consultores/felipe-soares"><img src="/es11-logo.png" alt="ES11 Capital" /></a><a href="/consultores/felipe-soares/artigos">← Todos os conteúdos</a></header><article className="single-article"><small>{article.category} · Felipe Soares · Publicado em {new Date(article.publishedAt).toLocaleDateString("pt-BR")} · Atualizado em {new Date(article.updatedAt).toLocaleDateString("pt-BR")} · {article.readingTime}</small><h1>{article.title}</h1><p className="article-subtitle">{article.subtitle}</p><img className="article-featured" src={article.image} alt={article.imageAlt} /><div className="article-rule" />{article.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<aside><img src={consultant.image} alt="Felipe Soares" /><div><strong>Sobre Felipe Soares</strong><span>Sócio e Consultor Financeiro da ES11 Capital. Atua com estratégias patrimoniais para investidores, empresários, profissionais liberais e famílias.</span><a data-article-cta="true" data-position="article" href={consultant.whatsapp} target="_blank" rel="noreferrer">Conversar com Felipe →</a></div></aside><section className="related"><h2>Conteúdos relacionados</h2>{related.map((item) => <a key={item.slug} href={`/consultores/felipe-soares/artigos/${item.slug}`}>{item.title} →</a>)}</section><p className="article-disclaimer">A análise realizada pela ES11 Capital é personalizada e consultiva. Não há promessa de prazo de contemplação, rentabilidade ou resultado financeiro.</p></article></main>;
}
