import { articles, consultant, decisions, faq, specialties } from "./lib/felipe";
import { SiteHeader } from "./components/SiteHeader";

export default function Home() {
  const profileJsonLd = { "@context": "https://schema.org", "@type": ["ProfilePage", "Person"], name: consultant.name, jobTitle: consultant.role, url: consultant.profileUrl, image: consultant.image, worksFor: { "@type": "Organization", name: "ES11 Capital", url: "https://www.es11capital.com.br/" }, sameAs: ["https://www.instagram.com/felipennsoares/", "https://www.instagram.com/es11capital/"] };
  return (
    <main id="inicio">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(profileJsonLd) }} />
      <SiteHeader whatsapp={consultant.whatsapp} />

      <section className="hero">
        <div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" />
        <div className="container hero-grid">
          <div className="hero-copy">
            <p className="kicker">CONSULTOR FINANCEIRO Â· ES11 CAPITAL</p>
            <h1>Felipe Soares <span>â€” Consultor Financeiro da ES11 Capital</span></h1>
            <p className="hero-title">EstratÃ©gias patrimoniais para investidores e empresÃ¡rios que desejam crescer preservando liquidez.</p>
            <p className="hero-description">Atendimento consultivo para estruturar aquisiÃ§Ãµes, ampliar patrimÃ´nio e transformar objetivos em um planejamento de longo prazo.</p>
            <div className="hero-actions"><a className="gold-button" data-position="hero" href={consultant.whatsapp} target="_blank" rel="noreferrer">Agendar conversa com Felipe <b aria-hidden="true">â†’</b></a><a className="quiet-link" href="#como-funciona">Conhecer o atendimento <b aria-hidden="true">â†“</b></a></div>
            <div className="hero-points"><span>Atendimento consultivo</span><span>SÃ£o Paulo, SP Â· todo o Brasil</span><span>ES11 Capital</span></div>
          </div>
          <div className="hero-photo-wrap"><div className="photo-outline" /><img className="hero-photo" src="/felipe-soares-retrato.webp" alt="Felipe Soares, sÃ³cio e consultor financeiro da ES11 Capital" /><div className="photo-label"><strong>Felipe Soares</strong><small>EstratÃ©gia para o seu momento</small></div></div>
        </div>
      </section>

      <section className="about section" id="sobre"><div className="container about-grid"><div><p className="section-tag">SOBRE FELIPE</p><h2>PatrimÃ´nio nÃ£o se constrÃ³i por acaso. <em>Ele ganha direÃ§Ã£o.</em></h2></div><div className="about-copy"><p>Sou sÃ³cio da ES11 Capital e atuo com estratÃ©gias patrimoniais voltadas para pessoas e empresas que desejam construir patrimÃ´nio de forma inteligente.</p><p>Minha trajetÃ³ria comeÃ§ou na Ã¡rea comercial, onde desenvolvi uma visÃ£o consultiva focada em entender os objetivos de cada cliente e encontrar as melhores soluÃ§Ãµes. Hoje, ajudo clientes a transformar planejamento financeiro em crescimento patrimonial por meio de estratÃ©gias personalizadas.</p><blockquote>â€œMeu trabalho comeÃ§a antes da apresentaÃ§Ã£o de qualquer produto: comeÃ§a entendendo o objetivo, o momento financeiro e os planos futuros do cliente.â€</blockquote></div></div></section>

      <section className="difference"><div className="container difference-inner"><p className="section-tag">O DIFERENCIAL</p><h2>NÃ£o Ã© sobre apresentar um produto. Ã‰ sobre construir uma estratÃ©gia que faÃ§a sentido para vocÃª.</h2><p>Meu compromisso Ã© oferecer um atendimento consultivo e personalizado, acompanhando sua evoluÃ§Ã£o e ajudando na tomada de decisÃµes com mais seguranÃ§a.</p></div></section>

      <section className="audiences section"><div className="container"><div className="section-heading"><div><p className="section-tag light">PARA QUEM Ã‰ O ATENDIMENTO</p><h2>Para quem pensa patrimÃ´nio <em>com seriedade.</em></h2></div><p>O ponto de partida Ã© entender o que vocÃª deseja construir, adquirir ou organizar - e definir caminhos compatÃ­veis com sua realidade.</p></div><div className="audience-grid"><article><span>01 / PRIORIDADE</span><h3>Investidores</h3><p>Para quem deseja ampliar patrimÃ´nio, avaliar aquisiÃ§Ãµes e usar tempo, liquidez e oportunidades de forma estratÃ©gica.</p></article><article><span>02</span><h3>EmpresÃ¡rios e profissionais liberais</h3><p>Para estruturar ativos e crescimento sem comprometer o fluxo pessoal ou empresarial.</p></article><article><span>03</span><h3>FamÃ­lias e empresas</h3><p>Para transformar projetos de imÃ³veis, veÃ­culos, frota ou equipamentos em planejamento de longo prazo.</p></article></div></div></section>

      <section className="decisions section"><div className="container decisions-grid"><div className="decision-image"><img src="/felipe-soares-es11.webp" alt="Felipe Soares em reuniÃ£o na ES11 Capital" /><span>ES11 CAPITAL</span></div><div><p className="section-tag">EM QUAIS DECISÃ•ES POSSO AJUDAR</p><h2>Clareza antes da sua prÃ³xima decisÃ£o patrimonial.</h2><div className="decision-list">{decisions.map((decision) => <span key={decision}>{decision}</span>)}</div></div></div></section>

      <section className="specialties section" id="especialidades"><div className="container"><p className="section-tag">ESPECIALIDADES</p><div className="specialty-heading"><h2>EstratÃ©gias que respeitam o seu momento e <em>o seu futuro.</em></h2><a className="quiet-link navy-link" href={consultant.whatsapp} target="_blank" rel="noreferrer">Falar sobre meu objetivo <b aria-hidden="true">â†’</b></a></div><div className="specialty-grid">{specialties.map((item)=><article key={item.number}><span>{item.number}</span><i /><h3>{item.title}</h3><p>{item.text}</p><b aria-hidden="true">â†—</b></article>)}</div></div></section>

      <section className="method section" id="como-funciona"><div className="container"><div className="method-heading"><div><p className="section-tag light">COMO FUNCIONA</p><h2>Uma conversa estratÃ©gica para clarear <em>seu prÃ³ximo movimento.</em></h2></div><p>Meu atendimento Ã© estratÃ©gico, prÃ³ximo e didÃ¡tico. Antes de apresentar qualquer soluÃ§Ã£o, busco entender objetivos, realidade financeira e planos futuros.</p></div><div className="steps">{[["01","Objetivo","VocÃª apresenta o que deseja adquirir, construir ou organizar."],["02","DiagnÃ³stico","Entendemos momento financeiro, liquidez, prazo e prioridades."],["03","CenÃ¡rios","Avaliamos alternativas e seus possÃ­veis impactos."],["04","EstratÃ©gia","Apresentamos caminhos que podem fazer sentido."],["05","Acompanhamento","Caso avance, acompanho a execuÃ§Ã£o da estratÃ©gia."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><a className="gold-button method-button" data-position="method" href={consultant.whatsapp} target="_blank" rel="noreferrer">Quero conversar com Felipe <b aria-hidden="true">â†’</b></a></div></section>

      <section className="es11 section"><div className="container es11-inner"><div><img src="/es11-logo.png" alt="ES11 Capital" /><p className="section-tag">A ESTRUTURA DA ES11 CAPITAL</p><h2>Atendimento pessoal com uma estrutura maior por trÃ¡s.</h2></div><p>A ES11 Capital atua com planejamento e estruturaÃ§Ã£o patrimonial para investidores, empresÃ¡rios, profissionais liberais, famÃ­lias e empresas. Antes de recomendar qualquer soluÃ§Ã£o, sÃ£o considerados objetivo, liquidez, prazo, capacidade financeira, oportunidades e riscos.</p><a className="quiet-link navy-link" data-position="institutional" href="https://www.es11capital.com.br/" target="_blank" rel="noreferrer">Conhecer a ES11 Capital <b aria-hidden="true">â†—</b></a></div></section>

      <section className="content section" id="conteudos"><div className="container"><div className="section-heading content-heading"><div><p className="section-tag">CONTEÃšDOS DE FELIPE</p><h2>Ideias para decidir <em>com mais clareza.</em></h2></div><a className="quiet-link navy-link" href="/consultores/felipe-soares/artigos">Ver todos os artigos <b aria-hidden="true">â†’</b></a></div><div className="article-grid">{articles.slice(0, 3).map((article, index)=><article key={article.slug}><div className={`article-visual visual-${index+1}`}><img src={article.image} alt={article.imageAlt} /><span>{article.category}</span></div><div className="article-body"><small>{new Date(article.publishedAt).toLocaleDateString("pt-BR")} Â· {article.readingTime}</small><h3>{article.title}</h3><a data-article-cta="true" href={`/consultores/felipe-soares/artigos/${article.slug}`}>Ler artigo <b aria-hidden="true">â†’</b></a></div></article>)}</div></div></section>

      <section className="faq section" id="duvidas"><div className="container faq-grid"><div><p className="section-tag">DÃšVIDAS COMUNS</p><h2>Antes de decidir, <em>Ã© natural perguntar.</em></h2><p>Se o seu objetivo ainda nÃ£o estÃ¡ totalmente claro, a conversa Ã© justamente o lugar para comeÃ§ar.</p></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<b aria-hidden="true">+</b></summary><p>{a}</p></details>)}</div></div></section>

      <section className="final-cta"><div className="container final-cta-inner"><p className="section-tag light">SEU PRÃ“XIMO PASSO</p><h2>Objetivos claros. <em>Resultados construÃ­dos com estratÃ©gia.</em></h2><p>Se vocÃª tem um objetivo, mas ainda nÃ£o sabe qual Ã© o melhor caminho para alcanÃ§Ã¡-lo, conte comigo. Vamos analisar sua situaÃ§Ã£o e montar um planejamento para o seu momento.</p><a className="gold-button" data-position="final-cta" href={consultant.whatsapp} target="_blank" rel="noreferrer">Agendar conversa com Felipe <b aria-hidden="true">â†’</b></a></div></section>

      <footer><div className="container footer-grid"><div><img src="/es11-logo.png" alt="ES11 Capital" /><p>Felipe Soares<br /><span>SÃ³cio e Consultor Financeiro</span></p></div><div><small>CONTATO</small><a data-position="footer" href={consultant.whatsapp} target="_blank" rel="noreferrer">(11) 97124-4859</a><p>SÃ£o Paulo, SP Â· atendimento em todo o Brasil</p></div><div><small>SIGA</small><a data-position="footer" href="https://www.instagram.com/felipennsoares/" target="_blank" rel="noreferrer">@felipennsoares â†—</a><a data-position="footer" href="https://www.instagram.com/es11capital/" target="_blank" rel="noreferrer">@es11capital â†—</a></div></div><div className="container footer-bottom"><span>Â© {new Date().getFullYear()} Felipe Soares Â· ES11 Capital</span><span>A anÃ¡lise realizada pela ES11 Capital Ã© personalizada e consultiva. NÃ£o hÃ¡ promessa de prazo de contemplaÃ§Ã£o, rentabilidade ou resultado financeiro.</span></div></footer>
    </main>
  );
}


